<a href="https://colab.research.google.com/github/wellalbuquerque/Resolve-um-sistema-linear-por-fatoracao-LU-com-estrategia-de-pivoteamento-parcial/blob/master/Res_LU_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# encoding: utf-8
# encoding: iso-8859-1
# encoding: win-1252
#Solve the system of linear equations through 
#LU factorization with the partial pivoting strategy:
#Atividade desenvolvida para a disciplina G_EB406A_2021S1 - Cálculo Numérico
#The University of Campinas -UNICAMP
#A = np.array([[1,-2,7,2],[2,5,-3,1],[9,-6,4,1],[4,-3,-6,7]])=b=([-18, 31,35,15]) #
#Desenvolvido por: José Wellington Albuquerque
#Disponível em:
#https://github.com/wellalbuquerque/Resolve-um-sistema-linear-por-fatoracao-LU-com-estrategia-de-pivoteamento-parcial/blob/dcf3f29b551b6d1674d523937680e654a097e80c/res_lu_final.ipynb

import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,-2,7,2],[2,5,-3,1],[9,-6,4,1],[4,-3,-6,7]])
b = np.array([-18, 31,35,15])
print("A matriz A é:\n\n",+A,"\n")

print("A matriz b é: \n\n",+b,"\n")

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
####np.dot retorna o produto escalar de duas matrizes.
print(P)
print(L)
print(U)
#implementa a resolução para X:
from numpy.linalg import *
import time as time

A = np.array([[1, -2, 7,2], [2, 5, -3,1], [9, -6, 4,1],[4, -3, -6,7]]);
b = np.array([-18, 31,35,15])

start = time.time()
x = solve(A, b); 
ttaken = time.time()-start

print('\n A solução para X é de aproximadamente:\n\n %s \n\n Calculado em apenas %f segundos!\n\n' % (x, ttaken))
# Imprime a solução para X e retorna o tempo de processamento do calculo no Colab!

A matriz A é:

 [[ 1 -2  7  2]
 [ 2  5 -3  1]
 [ 9 -6  4  1]
 [ 4 -3 -6  7]] 

A matriz b é: 

 [-18  31  35  15] 

[[ 9. -6.  4.  1.]
 [ 2.  5. -3.  1.]
 [ 4. -3. -6.  7.]
 [ 1. -2.  7.  2.]]
[[ 9. -6.  4.  1.]
 [ 2.  5. -3.  1.]
 [ 4. -3. -6.  7.]
 [ 1. -2.  7.  2.]]
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.22222222  1.          0.          0.        ]
 [ 0.44444444 -0.05263158  1.          0.        ]
 [ 0.11111111 -0.21052632 -0.71868132  1.        ]]
[[ 9.         -6.          4.          1.        ]
 [ 0.          6.33333333 -3.88888889  0.77777778]
 [ 0.          0.         -7.98245614  6.59649123]
 [ 0.          0.          0.          6.79340659]]

 A solução para X é de aproximadamente:

 [ 6.87609188  2.68003882 -2.09317373 -2.43189906] 

 Calculado em apenas 0.000163 segundos!




In [ ]:
# Lembre-se de conectar seu Google Drive ao Colab para evitar este erros como este:
#"[Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/'/content"
%cd /content/drive/MyDrive/Colab Notebooks/
# comando para entrar no diretório do driver %cd seu /diretorio/Colab Notebooks/

In [ ]:
#Install Latex.
!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended

!jupyter nbconvert --to html Res_LU_final.ipynb

#Converte e exporta de *.ipynb para *.html e PDF e salva em seu Google Drive!!!
!jupyter nbconvert --to pdf Res_LU_final.ipynb